export const IS_LOADING = "IS_LOADING";

// Auth
export const USER_INFO = "USER_INFO";
export const USER_LOGOUT = "USER_LOGOUT";

// home  / dashboard
export const GET_DASHBOARD_DATA = "GET_DASHBOARD_DATA";

export const ITEM_DEATILS = "ITEM_DEATILS";


// drawer
export const TOGGLE_DRAWER = "TOGGLE_DRAWER"

//catalogue
export const GET_CATALOGUE_CATEGORY_LIST_DATA="GET_CATALOGUE_CATEGORY_LIST_DATA"
export const GET_CATALOGUE_CATEGORY_SEARCH_LIST_DATA="GET_CATALOGUE_CATEGORY_SEARCH_LIST_DATA"
export const GET_CATALOGUE_CATEGORY_PRODUCT_LIST_DATA="GET_CATALOGUE_CATEGORY_PRODUCT_LIST_DATA"
export const GET_CATALOGUE_FILTER_FROM_LIST_DATA="GET_CATALOGUE_FILTER_FROM_LIST_DATA"
export const GET_PRODUCT_DETAILS_DATA="GET_PRODUCT_DETAILS_DATA"
export const GET_PRODUCT_SPECS_DETAILS_DATA="GET_PRODUCT_SPECS_DETAILS_DATA"
export const GET_PRODUCT_LOCATION_DETAILS_DATA="GET_PRODUCT_LOCATION_DETAILS_DATA"
export const GET_PAYMENT_DETAILS_LIST="GET_PAYMENT_DETAILS_LIST"
export const GET_PROFILE_DETAILS_LIST="GET_PROFILE_DETAILS_LIST"
export const GET_CART_DETAILS_DATA="GET_CART_DETAILS_DATA"
export const GET_ACTIVE_RENTALS_DETAILS_DATA="GET_ACTIVE_RENTALS_DETAILS_DATA"