export const icons = {
  appLogo: require("../../assets/icon/logo.png"),

  backIcon: require("../../assets/icon/backIcon.png"),
  bgImge: require("../../assets/icon/bgImge.png"),
  cartIcon: require("../../assets/icon/cartIcon.png"),
  facebook: require("../../assets/icon/facebook.png"),
  toolscab: require("../../assets/icon/toolscab.png"),
  homeFooter: require("../../assets/icon/homeFooter.png"),
  image1: require("../../assets/icon/image1.png"),
  image2: require("../../assets/icon/image2.png"),
  image3: require("../../assets/icon/image3.png"),
  image4: require("../../assets/icon/image4.png"),
  image5: require("../../assets/icon/image5.png"),
  image7: require("../../assets/icon/image7.png"),
  image8: require("../../assets/icon/image8.png"),
  image9: require("../../assets/icon/image9.png"),
  done: require("../../assets/icon/done.png"),
  instagram: require("../../assets/icon/instagram.png"),
  map: require("../../assets/icon/map.png"),
  notification: require("../../assets/icon/notification.png"),
  phoneImg: require("../../assets/icon/phoneImg1.png"),
  userIcone: require("../../assets/icon/userIcone.png"),
  userImg: require("../../assets/icon/userImg.png"),
  mapImg: require("../../assets/icon/mapImg.png"),
  rightBack: require("../../assets/icon/rightBack.png"),
  TarkRentImg: require("../../assets/icon/TarkRentImg.png"),
  closecircle: require("../../assets/icon/closecircle.png"),
  downarrow: require("../../assets/icon/downarrow.png"),
  image6: require("../../assets/icon/image6.png"),
  imageBg: require("../../assets/icon/imageBg.png"),
  pay3: require("../../assets/icon/pay3.png"),
  pay1: require("../../assets/icon/pay1.png"),
  pay2: require("../../assets/icon/pay2.png"),
  pen: require("../../assets/icon/pen.png"),
  save: require("../../assets/icon/save.png"),
  dotsthreefill: require("../../assets/icon/dotsthreefill.png"),
  dotsthreefill1: require("../../assets/icon/dotsthreefill1.png"),
  search:require("../../assets/icon/search.png"),
  epquestion:require("../../assets/icon/epquestion.png"),

  menuIcon: require("../../assets/icon/menuIcon.png"),
  closeIcon: require("../../assets/icon/close.png"),
  filterClose: require("../../assets/icon/filterClose.png"),
  checkbox:require("../../assets/icon/checkbox.png"),
  bottomArrow:require("../../assets/icon/bottomArrow.png"),
  buttonIcon:require("../../assets/icon/button.png"),
  stpes:require("../../assets/icon/stpes.png"),
  esimene:require("../../assets/icon/esimene.png"),
  right_arrow:require("../../assets/icon/right-arrow.png"),
  filterMobileIcon:require('../../assets/icon/filterMobileIcon.png'),
  mobileFooterbg:require('../../assets/icon/mobileFooterbg.png'),
  commonicon:require('../../assets/icon/commonicon.png'),
  ellipse1:require('../../assets/icon/ellipse1.png'),
  ellipse:require('../../assets/icon/ellipse.png'),
  defultIcon:require('../../assets/icon/defultIcon.jpeg'),
  qrcode:require('../../assets/icon/qrcode.png'),
  bin:require('../../assets/icon/bin.png'),
  logout:require('../../assets/icon/logout.png'),
  turnoff:require('../../assets/icon/turnoff.png'),
  searchboxPointer:require('../../assets/icon/searchboxPointer.png'),
};

export const image = {
  esimenetark: require("../../assets/Image/esimenetark.png"),
  toolscab2: require("../../assets/Image/toolscab2.png"),
  loikurid: require("../../assets/Image/loikurid.png"),
  pesurid: require("../../assets/Image/pesurid.png"),
  puhurid: require("../../assets/Image/puhurid.png"),
  saed: require("../../assets/Image/saed.png"),
  tolmuimejad: require("../../assets/Image/tolmuimejad.png"),
  trellid: require("../../assets/Image/trellid.png"),
}